CREATE TABLE IF NOT EXISTS company (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    legal_name VARCHAR(255),
    logo_url TEXT,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) DEFAULT 'India',
    pin_code VARCHAR(20) NOT NULL,
    tax_id VARCHAR(100),
    gst_number VARCHAR(50),
    pan_number VARCHAR(50) NOT NULL UNIQUE,
    tan_number VARCHAR(50),
    pf_number VARCHAR(50),
    esic_number VARCHAR(50),
    contact_email VARCHAR(255) NOT NULL UNIQUE,
    contact_phone VARCHAR(20) NOT NULL,
    website VARCHAR(255),
    financial_year_start DATE DEFAULT '2024-04-01',
    financial_year_end DATE DEFAULT '2025-03-31',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);